(ns natal-wrapper.core)

(set! js/window.React (js/require "react"))
(def ReactNative (js/require "react-native"))
(def MUI (js/require "react-native-material-design"))


(defn create-element [rn-comp opts & children]
  (apply js/React.createElement rn-comp (clj->js opts) children))

(def activity-indicator (partial create-element (.-ActivityIndicator ReactNative)))
(def app-registry (.-AppRegistry ReactNative))
(def drawer-layout-android (partial create-element (.-DrawerLayoutAndroid ReactNative)))
(def flat-list (partial create-element (.-FlatList ReactNative)))
(def image (partial create-element (.-Image ReactNative)))
(def keyboard-avoiding-view (partial create-element (.-KeyboardAvoidingView ReactNative)))
(def list-view (partial create-element (.-ListView ReactNative)))
(def modal (partial create-element (.-Modal ReactNative)))
(def picker (partial create-element (.-Picker ReactNative)))
(def progress-bar-android (partial create-element (.-ProgressBarAndroid ReactNative)))
(def progress-view-ios (partial create-element (.-ProgressViewIOS ReactNative)))
(def refresh-control (partial create-element (.-RefreshControl ReactNative)))
(def scroll-view (partial create-element (.-ScrollView ReactNative)))
(def section-list (partial create-element (.-SectionList ReactNative)))
(def segmented-control-ios (partial create-element (.-SegmentedControlIOS ReactNative)))
(def slider (partial create-element (.-Slider ReactNative)))
(def snapshot-view-ios (partial create-element (.-SnapshotViewIOS ReactNative)))
(def status-bar (partial create-element (.-StatusBar ReactNative)))
(def switch (partial create-element (.-Switch ReactNative)))
(def tab-bar-ios (partial create-element (.-TabBarIOS ReactNative)))
(def tab-bar-ios.item (partial create-element (.-TabBarIOS.Item ReactNative)))
(def text (partial create-element (.-Text ReactNative)))
(def text-input (partial create-element (.-TextInput ReactNative)))
(def toolbar-android (partial create-element (.-ToolbarAndroid ReactNative)))
(def touchable-highlight (partial create-element (.-TouchableHighlight ReactNative)))
(def touchable-native-feedback (partial create-element (.-TouchableNativeFeedback ReactNative)))
(def touchable-opacity (partial create-element (.-TouchableOpacity ReactNative)))
(def touchable-without-feedback (partial create-element (.-TouchableWithoutFeedback ReactNative)))
(def view (partial create-element (.-View ReactNative)))
(def view-pager-android (partial create-element (.-ViewPagerAndroid ReactNative)))
(def virtualized-list (partial create-element (.-VirtualizedList ReactNative))
(def web-view (partial create-element (.-WebView ReactNative)))    
